### ISSUE TITLE
Add LSP support

### ISSUE THREAD

**Issue by gdamore** [staysail/zed-d#1]
We really want to have LSP (Serve-D) support in this extension.

**Comment by maxbrunsfeld** [comment]
LSP is now partly supported, we just need to document it. In the meantime, for examples, you can view these extensions: https://github.com/zed-industries/zed/tree/main/extensions.

We're actively adding to the extension API in that area.

**Comment by gdamore** [comment]
This is now fixed (for 0.129 and better): https://github.com/staysail/zed-d/commit/e4391cc9cf9cc962c5300c859daaeda2bd8bcb6b
